#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 2021 Research Data Management Series
name_fr:

# Name of the author
author: CAUL DPSC

# Short bio or description (displayed in the header)
description: Brought to you by the <b>CAUL-CBUA Digital Preservation and Stewardship Committee</b> in partnership with <b>Compute Canada / Acenet</b> and <b>NDRIO-Portage</b>. The francization of the event is made possible through the collaboration of the members of the <b>Research Data Management Working Group of the BCI's Libraries Subcommittee</b>.
description_fr: Présenté par <b>le Comité de préservation et de gestion des données numériques du CAUL-CBUA</b> en partenariat avec <b>Calcul Canada / Acenet</b> et <b>NOIRN-Portage</b>. La francisation de l’événement est rendue possible grâce à <b>la collaboration des membres du Groupe de travail sur la gestion des données de recherche du Sous-comité des bibliothèques du Bureau de la coopération interuniversitaire</b>.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/caul-logo.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: #amit.d.merchant@gmail.com
  facebook:
  flickr:
  github: #amitmerchant1990/reverie
  instagram:
  linkedin: 
  pinterest:
  rss: rss
  twitter: #amit_merchant
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: #UA-43339302-11

# For newer "GA4" analytics, use the following instead of the "UA" entry above
#google_analytics_ga4: G-GABC1DEFG

# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
url: http://caul-dpsc.github.io
enforce_ssl: https://caul-dpsc.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: #"/caul-dpsc.github.io"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

